In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:/Users/ATAISH NEHRA/Downloads/DS5500 Raw datasets/Forest and carbon world only.csv")

In [3]:
df.columns

Index(['ObjectId', 'Country', 'ISO2', 'ISO3', 'Indicator', 'Unit', 'Source',
       'CTS_Code', 'CTS_Name', 'CTS_Full_Descriptor', '1992', '1993', '1994',
       '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003',
       '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012',
       '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020'],
      dtype='object')

In [4]:
df

,ObjectId,Country,ISO2,ISO3,Indicator,Unit,Source,CTS_Code,CTS_Name,CTS_Full_Descriptor,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,1330,World,NaN,WLD,Carbon stocks in forests,Million tonnes,Food and Agriculture Organization of the Unite...,NaN,NaN,NaN,...,2.938346e+05,2.940146e+05,2.941946e+05,2.943746e+05,2.945546e+05,2.947507e+05,2.944740e+05,2.944503e+05,2.942958e+05,2.941356e+05
1,1331,World,NaN,WLD,Forest area,1000 HA,Food and Agriculture Organization of the Unite...,NaN,NaN,NaN,...,4.101823e+06,4.097333e+06,4.092844e+06,4.088354e+06,4.083864e+06,4.080600e+06,4.073753e+06,4.068920e+06,4.063839e+06,4.058927e+06
2,1332,World,NaN,WLD,Index of carbon stocks in forests,Index,Food and Agriculture Organization of the Unite...,NaN,NaN,NaN,...,9.895126e+01,9.901187e+01,9.907248e+01,9.913310e+01,9.919371e+01,9.925976e+01,9.916659e+01,9.915860e+01,9.910657e+01,9.905263e+01
3,1333,World,NaN,WLD,Index of forest extent,Index,Food and Agriculture Organization of the Unite...,NaN,NaN,NaN,...,9.718218e+01,9.707580e+01,9.696943e+01,9.686305e+01,9.675667e+01,9.667934e+01,9.651714e+01,9.640261e+01,9.628225e+01,9.616586e+01
4,1334,World,NaN,WLD,Land area,1000 HA,Food and Agriculture Organization of the Unite...,NaN,NaN,NaN,...,1.301345e+07,1.302585e+07,1.302568e+07,1.302561e+07,1.302598e+07,1.302696e+07,1.302623e+07,1.302630e+07,1.302629e+07,1.302624e+07
5,1335,World,NaN,WLD,Share of forest area,Percent,Food and Agriculture Organization of the Unite...,NaN,NaN,NaN,...,3.151988e+01,3.145540e+01,3.142135e+01,3.138703e+01,3.135168e+01,3.132427e+01,3.127346e+01,3.123619e+01,3.119720e+01,3.115962e+01

In [5]:
# Define the columns to keep
columns_to_keep = ['Indicator', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', 
                   '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', 
                   '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020']

In [6]:
# Filter the DataFrame to keep only the specified columns
df_filtered = df[columns_to_keep]

In [8]:
# Display the first few rows of the filtered DataFrame
df_filtered.head(6)

,Indicator,1992,1993,1994,1995,1996,1997,1998,1999,2000,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Carbon stocks in forests,2.969488e+05,2.967239e+05,2.964990e+05,2.962741e+05,2.960492e+05,2.958243e+05,2.955994e+05,2.953745e+05,2.951496e+05,...,2.938346e+05,2.940146e+05,2.941946e+05,2.943746e+05,2.945546e+05,2.947507e+05,2.944740e+05,2.944503e+05,2.942958e+05,2.941356e+05
1,Forest area,4.220757e+06,4.212918e+06,4.205080e+06,4.197241e+06,4.189403e+06,4.181565e+06,4.173726e+06,4.165888e+06,4.158050e+06,...,4.101823e+06,4.097333e+06,4.092844e+06,4.088354e+06,4.083864e+06,4.080600e+06,4.073753e+06,4.068920e+06,4.063839e+06,4.058927e+06
2,Index of carbon stocks in forests,1.000000e+02,9.992426e+01,9.984853e+01,9.977279e+01,9.969705e+01,9.962132e+01,9.954558e+01,9.946984e+01,9.939410e+01,...,9.895126e+01,9.901187e+01,9.907248e+01,9.913310e+01,9.919371e+01,9.925976e+01,9.916659e+01,9.915860e+01,9.910657e+01,9.905263e+01
3,Index of forest extent,1.000000e+02,9.981429e+01,9.962858e+01,9.944287e+01,9.925716e+01,9.907145e+01,9.888574e+01,9.870003e+01,9.851432e+01,...,9.718218e+01,9.707580e+01,9.696943e+01,9.686305e+01,9.675667e+01,9.667934e+01,9.651714e+01,9.640261e+01,9.628225e+01,9.616586e+01
4,Land area,1.299094e+07,1.299057e+07,1.298936e+07,1.298906e+07,1.298901e+07,1.299595e+07,1.299334e+07,1.299402e+07,1.299993e+07,...,1.301345e+07,1.302585e+07,1.302568e+07,1.302561e+07,1.302598e+07,1.302696e+07,1.302623e+07,1.302630e+07,1.302629e+07,1.302624e+07
5,Share of forest area,3.249000e+01,3.243060e+01,3.237326e+01,3.231367e+01,3.225344e+01,3.217591e+01,3.212203e+01,3.206003e+01,3.198518e+01,...,3.151988e+01,3.145540e+01,3.142135e+01,3.138703e+01,3.135168e+01,3.132427e+01,3.127346e+01,3.123619e+01,3.119720e+01,3.115962e+01

In [9]:
# Assuming df_filtered is your current DataFrame
# Pivot the DataFrame
df_pivoted = df_filtered.pivot_table(values=['1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', 
                                             '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', 
                                             '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', 
                                             '2019', '2020'], 
                                     index='Indicator', 
                                     aggfunc='first').transpose()

In [10]:
# Reset the index to make the years a column
df_pivoted.reset_index(inplace=True)

In [11]:
df_pivoted.rename(columns={'index': 'Year'}, inplace=True)

In [13]:
# Display the first few rows of the pivoted DataFrame
df_pivoted

Indicator,Year,Carbon stocks in forests,Forest area,Index of carbon stocks in forests,Index of forest extent,Land area,Share of forest area
0,1992,296948.8291,4220756.642,100.000000,100.000000,12990940.44,32.490001
1,1993,296723.9289,4212918.252,99.924263,99.814289,12990565.84,32.430599
2,1994,296499.0290,4205079.862,99.848526,99.628579,12989361.14,32.373262
3,1995,296274.1290,4197241.472,99.772789,99.442868,12989059.14,32.313668
4,1996,296049.2285,4189403.083,99.697052,99.257158,12989013.64,32.253435
5,1997,295824.3288,4181564.692,99.621315,99.071447,12995947.64,32.175912
6,1998,295599.4295,4173726.302,99.545578,98.885737,12993344.44,32.122032
7,1999,295374.5288,4165887.912,99.469841,98.700026,12994023.24,32.060031
8,2000,295149.6290,4158049.522,99.394104,98.514316,12999925.49,31.985180
9,2001,295000.1375,4152876.264,99.343762,98.391749,12999806.91,31.945677
10,2002,294850.6476,4147703.007,99.293420,98.269182,12999588.13,31.906419
11,2003,294701.1574,4142529.749,99.243078,98.146614,13000301.79,31.864874
12,2004,294551.6671,4137356.491,99.192736,98.024047,13014956.86,31.789245
13,2005,294402.1767,4132183.233,99.142394,97.901480,13015231.01,31.748827
14,2006,294252.6864,4127009.975,99.092051,97.778913,13015009.79,31.709619
15,2007,294103.1955,4121836.718,99.041709,97.656346,13014987.97,31.669923
16,2008,293953.7052,4116663.460,98.991367,97.533779,13013402.01,31.634030
17,2009,293804.2152,4111490.202,98.941025,97.411212,13013246.14,31.594655
18,2010,293654.7250,4106316.944,98.890683,97.288645,13013483.88,31.554325
19,2011,293834.6057,4101823.291,98.951259,97.182179,13013448.42,31.519880
20,2012,294014.5940,4097333.397,99.011872,97.075803,13025851.79,31.455397
21,2013,294194.5829,4092843.503,99.072485,96.969426,13025675.60,31.421353
22,2014,294374.5721,4088353.610,99.133097,96.863050,13025613.71,31.387033
23,2015,294554.5616,4083863.716,99.193710,96.756673,13025979.06,31.351683
24,2016,294750.6810,4080599.782,99.259755,96.679343,13026958.88,31.324270
25,2017,294474.0169,4073753.425,99.166586,96.517136,13026230.26,31.273464
26,2018,294450.3036,4068919.514,99.158601,96.402609,13026300.91,31.236186
27,2019,294295.8080,4063839.320,99.106573,96.282247,13026294.74,31.197201
28,2020,294135.6234,4058927.050,99.052629,96.165863,13026238.97,31.159624

In [17]:
# Save the pivoted DataFrame to a CSV file
df_pivoted.to_csv("C:/Users/ATAISH NEHRA/Downloads/Cleaned Datasets/Forest and Carbon_cleaned.csv", index=False)