In [1]:
import pandas as pd

In [2]:
# Load the original CSV file
file_path = "C:/Users/ATAISH NEHRA/Downloads/Forest and Carbon top 30.csv"
df = pd.read_csv(file_path)

In [3]:
df

,ObjectId,Country,ISO2,ISO3,Indicator,Unit,Source,CTS_Code,CTS_Name,CTS_Full_Descriptor,...,F2011,F2012,F2013,F2014,F2015,F2016,F2017,F2018,F2019,F2020
0,7,"Afghanistan, Islamic Rep. of",AF,AFG,Forest area,1000 HA,Food and Agriculture Organization of the Unite...,NaN,NaN,NaN,...,1208.440000,1208.440000,1208.440000,1208.440000,1208.440000,1208.440000,1208.440000,1208.440000,1208.440000,1208.440000
1,8,"Afghanistan, Islamic Rep. of",AF,AFG,Index of forest extent,Index,Food and Agriculture Organization of the Unite...,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
2,9,"Afghanistan, Islamic Rep. of",AF,AFG,Land area,1000 HA,Food and Agriculture Organization of the Unite...,NaN,NaN,NaN,...,65223.000000,65223.000000,65223.000000,65223.000000,65223.000000,65223.000000,65223.000000,65223.000000,65223.000000,65223.000000
3,10,"Afghanistan, Islamic Rep. of",AF,AFG,Share of forest area,Percent,Food and Agriculture Organization of the Unite...,NaN,NaN,NaN,...,1.852782,1.852782,1.852782,1.852782,1.852782,1.852782,1.852782,1.852782,1.852782,1.852782
4,63,Argentina,AR,ARG,Carbon stocks in forests,Million tonnes,Food and Agriculture Organization of the Unite...,NaN,NaN,NaN,...,3283.805500,3266.731500,3249.657500,3232.583500,3215.509500,3209.666400,3201.720200,3194.361400,3186.745900,3179.032000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,1309,Vietnam,VN,VNM,Forest area,1000 HA,Food and Agriculture Organization of the Unite...,NaN,NaN,NaN,...,13522.820000,13657.580000,13792.340000,13927.100000,14061.860000,14377.680000,14415.390000,14491.290000,14567.190000,14643.090000
174,1310,Vietnam,VN,VNM,Index of carbon stocks in forests,Index,Food and Agriculture Organization of the Unite...,NaN,NaN,NaN,...,140.581976,142.746345,144.910684,147.075053,149.239421,151.523600,153.897231,154.873085,155.060184,155.993568
175,1311,Vietnam,VN,VNM,Index of forest extent,Index,Food and Agriculture Organization of the Unite...,NaN,NaN,NaN,...,137.181834,138.548903,139.915971,141.283040,142.650109,145.853935,146.236483,147.006448,147.776413,148.546379
176,1312,Vietnam,VN,VNM,Land area,1000 HA,Food and Agriculture Organization of the Unite...,NaN,NaN,NaN,...,31328.400000,31345.700000,31300.733000,31337.100000,31338.300000,31338.700000,31340.300000,31342.900000,31342.900000,31342.900000
177,1313,Vietnam,VN,VNM,Share of forest area,Percent,Food and Agriculture Organization of the Unite...,NaN,NaN,NaN,...,43.164732,43.570825,44.063952,44.442849,44.871164,45.878355,45.996337,46.234682,46.476842,46.719002

In [4]:
# Select specific columns
columns_to_keep = ['Country', 'Indicator'] + [f'F{year}' for year in range(1992, 2021)]
df_filtered = df[columns_to_keep]

In [5]:
# Rename columns from 'FYear' to 'Year'
df_filtered.columns = ['Country', 'Indicator'] + [str(year) for year in range(1992, 2021)]

In [6]:
# Melt the DataFrame to long format
df_long = pd.melt(df_filtered, id_vars=['Country', 'Indicator'], var_name='Year', value_name='Value')

In [7]:
# Pivot the DataFrame to wide format based on 'Country', 'Year', and 'Indicator'
df_wide = df_long.pivot_table(index=['Country', 'Year'], columns='Indicator', values='Value', aggfunc='first').reset_index()

In [8]:
df_filtered_countries = df_wide

In [9]:
df_filtered_countries

Indicator,Country,Year,Carbon stocks in forests,Forest area,Index of carbon stocks in forests,Index of forest extent,Land area,Share of forest area
0,"Afghanistan, Islamic Rep. of",1992,NaN,1208.44,NaN,100.000000,65223.0,1.852782
1,"Afghanistan, Islamic Rep. of",1993,NaN,1208.44,NaN,100.000000,65223.0,1.852782
2,"Afghanistan, Islamic Rep. of",1994,NaN,1208.44,NaN,100.000000,65223.0,1.852782
3,"Afghanistan, Islamic Rep. of",1995,NaN,1208.44,NaN,100.000000,65223.0,1.852782
4,"Afghanistan, Islamic Rep. of",1996,NaN,1208.44,NaN,100.000000,65223.0,1.852782
...,...,...,...,...,...,...,...,...
865,Vietnam,2016,530.5364,14377.68,151.523600,145.853935,31338.7,45.878355
866,Vietnam,2017,538.8473,14415.39,153.897231,146.236483,31340.3,45.996337
867,Vietnam,2018,542.2641,14491.29,154.873085,147.006448,31342.9,46.234682
868,Vietnam,2019,542.9192,14567.19,155.060184,147.776413,31342.9,46.476842
869,Vietnam,2020,546.1873,14643.09,155.993568,148.546379,31342.9,46.719002

In [10]:
# Save the filtered dataset to a CSV file
csv_file_path = 'C:/Users/ATAISH NEHRA/Downloads/Cleaned Datasets/Forest and Carbon top 30 clean.csv'
df_filtered_countries.to_csv(csv_file_path, index=False)

In [11]:
# Load the dataset
file_path = "C:/Users/ATAISH NEHRA/Downloads/Cleaned Datasets/Forest and Carbon top 30 clean.csv"
df = pd.read_csv(file_path)

In [12]:
df

,Country,Year,Carbon stocks in forests,Forest area,Index of carbon stocks in forests,Index of forest extent,Land area,Share of forest area
0,"Afghanistan, Islamic Rep. of",1992,NaN,1208.44,NaN,100.000000,65223.0,1.852782
1,"Afghanistan, Islamic Rep. of",1993,NaN,1208.44,NaN,100.000000,65223.0,1.852782
2,"Afghanistan, Islamic Rep. of",1994,NaN,1208.44,NaN,100.000000,65223.0,1.852782
3,"Afghanistan, Islamic Rep. of",1995,NaN,1208.44,NaN,100.000000,65223.0,1.852782
4,"Afghanistan, Islamic Rep. of",1996,NaN,1208.44,NaN,100.000000,65223.0,1.852782
...,...,...,...,...,...,...,...,...
865,Vietnam,2016,530.5364,14377.68,151.523600,145.853935,31338.7,45.878355
866,Vietnam,2017,538.8473,14415.39,153.897231,146.236483,31340.3,45.996337
867,Vietnam,2018,542.2641,14491.29,154.873085,147.006448,31342.9,46.234682
868,Vietnam,2019,542.9192,14567.19,155.060184,147.776413,31342.9,46.476842
869,Vietnam,2020,546.1873,14643.09,155.993568,148.546379,31342.9,46.719002

In [13]:
# Define the geographically closest countries to Afghanistan for imputation
closest_geographical_countries = ['Iran, Islamic Rep. of', 'Pakistan', 'China, P.R.: Mainland', 'India']

In [14]:
# List of columns identified for imputation
columns_to_impute = ['Carbon stocks in forests', 'Index of carbon stocks in forests', 'Index of forest extent', 'Land area', 'Share of forest area']

In [15]:
# Perform imputation for each column
for column in columns_to_impute:
    for year in df['Year'].unique():
        # Calculate the mean for the geographically closest countries for the given year and column
        mean_value_geographical_countries = df[(df['Country'].isin(closest_geographical_countries)) & (df['Year'] == year)][column].mean()
        
        # Only impute this mean value for Afghanistan for the same year where the value is NaN
        afghanistan_nan_rows = df[(df['Country'] == 'Afghanistan, Islamic Rep. of') & (df['Year'] == year) & (df[column].isna())]
        if not afghanistan_nan_rows.empty:
            df.loc[afghanistan_nan_rows.index, column] = mean_value_geographical_countries

In [17]:
# Display the imputed dataset for Afghanistan
afghanistan_data_after_imputation = df[df['Country'] == 'Afghanistan, Islamic Rep. of']
afghanistan_data_after_imputation

,Country,Year,Carbon stocks in forests,Forest area,Index of carbon stocks in forests,Index of forest extent,Land area,Share of forest area
0,"Afghanistan, Islamic Rep. of",1992,2120.071125,1208.44,100.000000,100.0,65223.0,1.852782
1,"Afghanistan, Islamic Rep. of",1993,2160.349425,1208.44,101.072442,100.0,65223.0,1.852782
2,"Afghanistan, Islamic Rep. of",1994,2200.627750,1208.44,102.144893,100.0,65223.0,1.852782
3,"Afghanistan, Islamic Rep. of",1995,2240.906000,1208.44,103.217332,100.0,65223.0,1.852782
4,"Afghanistan, Islamic Rep. of",1996,2281.184300,1208.44,104.289774,100.0,65223.0,1.852782
5,"Afghanistan, Islamic Rep. of",1997,2321.462625,1208.44,105.362225,100.0,65223.0,1.852782
6,"Afghanistan, Islamic Rep. of",1998,2361.740925,1208.44,106.434667,100.0,65223.0,1.852782
7,"Afghanistan, Islamic Rep. of",1999,2402.019200,1208.44,107.507107,100.0,65223.0,1.852782
8,"Afghanistan, Islamic Rep. of",2000,2442.297475,1208.44,108.579546,100.0,65223.0,1.852782
9,"Afghanistan, Islamic Rep. of",2001,2467.687975,1208.44,109.226004,100.0,65223.0,1.852782
10,"Afghanistan, Islamic Rep. of",2002,2493.078475,1208.44,109.872462,100.0,65223.0,1.852782
11,"Afghanistan, Islamic Rep. of",2003,2518.468950,1208.44,110.518917,100.0,65223.0,1.852782
12,"Afghanistan, Islamic Rep. of",2004,2543.859475,1208.44,111.165376,100.0,65223.0,1.852782
13,"Afghanistan, Islamic Rep. of",2005,2569.249975,1208.44,111.811834,100.0,65223.0,1.852782
14,"Afghanistan, Islamic Rep. of",2006,2594.640425,1208.44,112.458288,100.0,65223.0,1.852782
15,"Afghanistan, Islamic Rep. of",2007,2620.030950,1208.44,113.104747,100.0,65223.0,1.852782
16,"Afghanistan, Islamic Rep. of",2008,2645.421425,1208.44,113.751201,100.0,65223.0,1.852782
17,"Afghanistan, Islamic Rep. of",2009,2670.811925,1208.44,114.397660,100.0,65223.0,1.852782
18,"Afghanistan, Islamic Rep. of",2010,2696.202425,1208.44,115.044118,100.0,65223.0,1.852782
19,"Afghanistan, Islamic Rep. of",2011,2749.213225,1208.44,116.021807,100.0,65223.0,1.852782
20,"Afghanistan, Islamic Rep. of",2012,2802.224025,1208.44,116.999496,100.0,65223.0,1.852782
21,"Afghanistan, Islamic Rep. of",2013,2855.234825,1208.44,117.977176,100.0,65223.0,1.852782
22,"Afghanistan, Islamic Rep. of",2014,2908.245625,1208.44,118.954865,100.0,65223.0,1.852782
23,"Afghanistan, Islamic Rep. of",2015,2961.256450,1208.44,119.932555,100.0,65223.0,1.852782
24,"Afghanistan, Islamic Rep. of",2016,3016.377600,1208.44,120.744521,100.0,65223.0,1.852782
25,"Afghanistan, Islamic Rep. of",2017,3061.368200,1208.44,121.585507,100.0,65223.0,1.852782
26,"Afghanistan, Islamic Rep. of",2018,3105.987825,1208.44,122.307197,100.0,65223.0,1.852782
27,"Afghanistan, Islamic Rep. of",2019,3149.965600,1208.44,123.019571,100.0,65223.0,1.852782
28,"Afghanistan, Islamic Rep. of",2020,3194.864850,1208.44,123.745838,100.0,65223.0,1.852782

In [18]:
df

,Country,Year,Carbon stocks in forests,Forest area,Index of carbon stocks in forests,Index of forest extent,Land area,Share of forest area
0,"Afghanistan, Islamic Rep. of",1992,2120.071125,1208.44,100.000000,100.000000,65223.0,1.852782
1,"Afghanistan, Islamic Rep. of",1993,2160.349425,1208.44,101.072442,100.000000,65223.0,1.852782
2,"Afghanistan, Islamic Rep. of",1994,2200.627750,1208.44,102.144893,100.000000,65223.0,1.852782
3,"Afghanistan, Islamic Rep. of",1995,2240.906000,1208.44,103.217332,100.000000,65223.0,1.852782
4,"Afghanistan, Islamic Rep. of",1996,2281.184300,1208.44,104.289774,100.000000,65223.0,1.852782
...,...,...,...,...,...,...,...,...
865,Vietnam,2016,530.536400,14377.68,151.523600,145.853935,31338.7,45.878355
866,Vietnam,2017,538.847300,14415.39,153.897231,146.236483,31340.3,45.996337
867,Vietnam,2018,542.264100,14491.29,154.873085,147.006448,31342.9,46.234682
868,Vietnam,2019,542.919200,14567.19,155.060184,147.776413,31342.9,46.476842
869,Vietnam,2020,546.187300,14643.09,155.993568,148.546379,31342.9,46.719002

In [19]:
# Define the path for the new CSV file
new_file_path = 'C:/Users/ATAISH NEHRA/Downloads/Cleaned Datasets/Forest and Carbon top 30 clean imputed.csv'

# Save the updated dataset to the new CSV file
df.to_csv(new_file_path, index=False)